# Generated by Django 5.2.4 on 2025-07-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='stop_loss_level',
            field=models.DecimalField(decimal_places=2, default=0.28, help_text='Fibonacci stop loss level (0.15, 0.28, 0.50, 0.63)', max_digits=4),
        ),
    ]
