# Generated by Django 5.2.4 on 2025-07-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersettings_stop_loss_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='break_even_buffer_pips',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Buffer pips for break-even activation at 1:1', max_digits=4),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='weekly_profit_threshold',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Weekly profit % threshold for 1:2 R:R upgrade', max_digits=4),
        ),
    ]
