# Generated by Django 5.2.4 on 2025-07-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usersettings_break_even_buffer_pips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='trade_london',
            field=models.BooleanField(default=True, help_text='Trade during London session (10:00-19:00 EET)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='trade_new_york',
            field=models.BooleanField(default=True, help_text='Trade during New York session (15:30-00:30 EET)'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='trade_tokyo',
            field=models.BooleanField(default=False, help_text='Trade during Tokyo session (03:00-12:00 EET)'),
        ),
    ]
