# Generated by Django 5.2.4 on 2025-07-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersettings_trade_london_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='metaquotes_enabled',
            field=models.BooleanField(default=False, help_text='Enable MetaQuotes push notifications'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='metaquotes_id',
            field=models.CharField(blank=True, help_text='MetaTrader ID for push notifications', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email for trading notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notification_email_enabled',
            field=models.BooleanField(default=True, help_text='Enable email notifications'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Enable SMS notifications'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='sms_phone',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Enable Telegram notifications'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username (without @)', max_length=50, null=True),
        ),
    ]
